run:
  timeout: 5m  # Максимальное время выполнения линтера (5 минут)
  modules-download-mode: readonly  # Режим загрузки модулей (только чтение)

linters:
  enable:
    #- revive       # Линтер для стиля кода (альтернатива golint)
    - govet        # Линтер для проверки ошибок, которые может найти компилятор
    - staticcheck  # Мощный статический анализатор кода
    - gosimple     # Линтер для упрощения кода
    - errcheck     # Проверяет, что ошибки обрабатываются
    - unconvert    # Ищет ненужные преобразования типов
    - ineffassign  # Ищет неиспользуемые присваивания
    - gocritic     # Линтер для критического анализа кода (стиль и производительность)
    - bodyclose    # Проверяет, что response.Body закрывается
    - gosec        # Линтер для поиска уязвимостей в коде
    - prealloc     # Рекомендует предварительное выделение памяти для срезов
    - misspell     # Ищет орфографические ошибки в строках
    - gofmt        # Проверяет форматирование кода
    - goimports    # Проверяет и организует импорты
    - wsl          # Линтер для строгого стиля (можно включить, если нужен строгий стиль)

linters-settings:
  enable:
    - shadow
  gocritic:
    enabled-tags:
      - performance  # Включает правила, связанные с производительностью
      - style        # Включает правила, связанные со стилем кода
      - experimental # Включает экспериментальные правила
  misspell:
    locale: US  # Указывает локаль для проверки орфографии (US)

issues:
  exclude-use-default: false  # Не использовать стандартные исключения
  max-issues-per-linter: 0    # Максимальное количество ошибок на линтер (0 = без ограничений)
  max-same-issues: 0          # Максимальное количество одинаковых ошибок (0 = без ограничений)