POST http://localhost:8081/api/feed
Content-Type: application/json

{
  "items": [
    {
      "rss": "https://habr.com/ru/rss/articles/top?limit=5",
      "filters": [
        "html-sanitizer",
        "max-length",
        "time-formatter-2006-01-02 15:04:05"
      ]
    },
    {
      "rss": "https://www.vedomosti.ru/rss/rubric/economics/global",
      "filters": [
        "html-sanitizer",
        "max-length",
        "size-of-8",
        "time-formatter-2006-01-02 15:04:05"
      ]
    }
  ]
}

###


