# yaml-language-server: $schema=../../configuration-schema.json
package: dto
output: models.gen.go
generate:
  models: true
output-options:
  # NOTE that this is only required for the `Unreferenced` type
  skip-prune: true